### ISSUE TITLE
equivalent of `#[serde(default)]`

### ISSUE THREAD

**Issue by cameron1024** [near/borsh-rs#278]
Hi, I was looking through the docs and wasn't able to find an answer to this, apologies if I missed it.

I'd like some way to be able to specify the default value for a field, similar to what `#[serde(default = ...)]` does. For context, I have two structs:
```rust
struct FooV1 {
  data: Vec<u8>,
}

struct FooV2 {
  data: Vec<u8>,
  something_else: i32,
}
```
I'd like to be able to take the serialized bytes of a `FooV1`, and deserialize them as a `FooV2` and set `something_else` to `0`. I tried `#[borsh(skip)]`, but this isn't quite what I'm looking for, because it also skips serializing if I have a `FooV2`, which I don't want (i.e. I want the serialize->deserialize round trip to not change the value of a `FooV2`)

Is this possible with the current macro? If not, would a PR that adds this be welcomed?

Thanks :grin:

**Comment by dj8yfo** [comment]
@cameron1024 probably, you could achieve optionality by expressing it with type: 
```rust
struct FooV3 {
  data: Vec<u8>,
  something_else: Option<i32>,
}
```
This juggling of encoded bytes of one type and decoding them as another type looks weird at first glance.
I've checked [`#serde[(default=...` doc](https://serde.rs/attr-default.html) , it's not obvious how alleged `#[borsh(default= ...` attribute must behave, given that borsh format doesn't encode field names and current field being decoded is assumed from context (position in stream). Thus atm it's either a field is always present in output, or always skipped. As already mentioned, optionality can be expressed with `Option<T>` without using any additional encoding attributes.

**Comment by frol** [comment]
> As already mentioned, optionality can be expressed with Option<T> without using any additional encoding attributes.

@dj8yfo Well, `None` still requires an explicit `0` byte in the input, so `FooV1 { data }` is not byte-equal to `FooV2 { data, something_else: None }`.

@cameron1024 Since Borsh does not have schema inside, it can become ambiguous if you randomly try to have `default` field value and expect to skip it. I recommend you manually implement [`BorshDeserialize`](https://docs.rs/borsh/latest/borsh/de/trait.BorshDeserialize.html) for `FooV2` that will handle it manually.
