### ISSUE TITLE
Add derive macro attribute to specify borsh crate

### ISSUE THREAD

**Issue by quasiyoke** [near/borsh-rs#95]
Add derive macro attribute like [serde container's `crate` attr](https://serde.rs/container-attrs.html#crate) ([test](https://github.com/serde-rs/serde/blob/1fcda0ebdb2cfa050df42fded93ba07c14e4b683/test_suite/tests/test_serde_path.rs)):

1. To be able to work with byte blobs built with legacy borsh.
1. To be able to use re-exported borsh crate for `BorshSerialize`, `BorshDeserialize` derives. 

```rs
#[derive(borsh::BorshSerialize)]
#[borsh(crate = "legacy_borsh")]
struct NearLog;
```

**Comment by cybersoulK** [comment]
I have this need also, and i can tey and prepare a PR

**Comment by iho** [comment]
@cybersoulK do you work on this?

**Comment by GentBinaku** [comment]
Can I work on this ?

**Comment by cybersoulK** [comment]
@iho 
I didn't end up working on it, because my new implementation does not require it. Borsh is only a way to serialize data, which should be imported in the original project anyways. The library allows the user to implement its own traits, which is a much better approach. if you want to automate the borsh derives, you can use macro_rules_attribute to create a local abstraction, instead of making it opinionated.
